version: '3.9'

services:
  netdeneb-node:
    image: netdeneb:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files:/files:ro
      - ./ISOs:/files/Public/ISOs:ro
      - ./art:/art:ro
      - ./thumbs:/thumbs

  netdeneb-proxy:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files:/files:ro
      - ./ISOs:/files/Public/ISOs:ro
      - ./art:/art:ro
      - ./thumbs:/thumbs:ro
      - ./other:/other:ro
